[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install --break-system-packages yt-dlp",
  "npm install"
]

[start]
cmd = "node server.js & sleep 2 && node bot.js"
