[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci", "python3 -m pip install yt-dlp"]

[start]
cmd = "node server.js & sleep 2 && node bot.js"
